### ISSUE TITLE
The New Session and Download App buttons are no longer working for me in either Chrome Desktop Windows or Chrome on Android.

### ISSUE THREAD

**Issue by HeatDeath76** [cloudpilot-emu/cloudpilot-emu#55]
Dragging a backup into the browser window works to create a new session. 
Also, it's not letting me restore backed up ToDoDB.pdb and MemoDB.pdb files for "uinknown reason".

**Comment by DirtyHairy** [comment]
Thanks for the note. Can confirm, I'll look for a fix. Weirdly enough, it works fine on Chrome for MacOS.

**Comment by DirtyHairy** [comment]
I just released 1.8.7. The open file dialog should work fine again now. I couldn't check on Android yet, but it works on windows. Can you check and confirm that the bug is fixed for you, too?

**Comment by HeatDeath76** [comment]
That fixed it. I can now create new sessions and load prc files again in Windows and Android.

It still won't let me load the backup databases for Address Book, Todo List, DateBook, and Memopad. Also shortcuts.pdb, network.pdb and one or two others. Basically the system databases.

Memopad is the one that hurts - I've got a bunch of PocketC source code in memopad that is a pain to copy/paste in there from my PC-based backups.

I can set that up as a separate issue if you'd like. It's happening on a Palm Pilot Professional OS 2.0 ROM. I wonder if it works on later OS versions?

**Comment by HeatDeath76** [comment]
1.8.8 does not appear to have fixed that. The affected pdb files are: 
AddressDB.pdb
DatebookDB.pdb
Graffiti ShortCuts.prc
MemoDB.pdb
Net Prefs.prc
ToDoDB.pdb

I saw Patience.prc and Patience History.pdb fail with the same error message when I happened to try to restore my entire backup zip while Patience was open. That makes me think it's symmetrical to the issue where an open DB won't back up - maybe PalmOS 2.0 keeps those db files open all the time and that blocks them from being overwritten when restored?

**Comment by DirtyHairy** [comment]
We can reuse this issue 😏 I just did another release with a fix for DB install errors --- previously, out-of-memory was displayed as "unkown reason". However, this only affected OS3+, on OS2 there is only "unknown error".

That said, restoring databases will fail if an DB is currently opened by an app. This prevents some system databases from being restored. The PIM apps (MemoPad & friends) do not fall in the category, but they will not restore if the app is currently open. This is tricky on OS2 as the last app stays open when the launcher is displayed. To make 100% sure that there are no open apps, reset the device before restoring.

If you continue to have issues: could you send me the problematic DB?

**Comment by DirtyHairy** [comment]
Didn't see your reply until I sent my own. The fix only addresses a wrong error message, nothing else is changed. Does the restore fail on a fresh OS2 device that hasn't started any app yet? Does it also fail on a newer PalmOS version?

**Comment by HeatDeath76** [comment]
Just did a reboot and then, first thing, before even touching the Palm UI, tried to load ToDoDB.pdb using the file load. Installation failed with unknown error. Here's the DB. Rename to ToDODB.pdb from .txt. Hopefully there won't be any encoding issues.
[ToDoDB.txt](https://github.com/cloudpilot-emu/cloudpilot-emu/files/12528036/ToDoDB.txt)

**Comment by DirtyHairy** [comment]
Indeed, the file does not install for me. Weirdly, I don't have any problems restoring a ToDoDB.pdb that I exported myself. Just to make sure, the md5 of the file I downloaded is 50d59662e98795a2ea35e65da5c1445a --- is that correct?

**Comment by DirtyHairy** [comment]
I don't think this is an encoding problem. After looking at that file for a while, I see why PalmOS does not want to install it: it is corrupt in a very specific way. The data is still there, and I can probably come up with a small tool that recovers this and any other databases that have been corrupted, but I am still mystified how the database became corrupt in the first place. You don't perchance still have an image of the virtual device from which you exported this database?

**Comment by HeatDeath76** [comment]
Unfortunately no.

**Comment by DirtyHairy** [comment]
OK, I think I have a working theory what is going wrong. PalmOS 1 and 2 use a special code path for backup as they don't support the necessary OS functions for backing up databases. The code is ported from dmitrygr's SASD, and I think I have found a bug in the handling of deleted records. Basically, you .pdb contain deleted records that have length zero that shouldn't be exported.

I'll do a more careful analysis and a fix later this week. I am pretty sure your data can be recovered, too. If I prepare a python script that removes the deleted records, can you run that on your bad databases?

**Comment by HeatDeath76** [comment]
Yep. thank you!

**Comment by DirtyHairy** [comment]
As a preview, here's the fixed version of your todos 😏:

[fixed.pdb.zip](https://github.com/cloudpilot-emu/cloudpilot-emu/files/12529045/fixed.pdb.zip)

**Comment by HeatDeath76** [comment]
That worked!

**Comment by DirtyHairy** [comment]
Can you try the following script on the broken files?

https://github.com/cloudpilot-emu/cloudpilot-emu/blob/master/tools/prctool.py

You run the script on broken databases like this:


```
    ./prctool.py fix-pdb ./bad.pdb ./good.pdb
```

This should fix your broken databases. I'll release a fix for the Cloudpilot bug that causes the issue in the first place later this week.

**Comment by HeatDeath76** [comment]
That worked to restore Datebook (1 record) and MemoDB! [ToDoDB, of course, you already tested it on.]
I didn't try it with AddressDB.pdb, which doesn't have any data I need, or Graffiti ShortCuts.prc or Net Prefs.prc, which might be separate issues entirely, and neither of which contain any data modified from a factory reset.

Thank you so much!

**Comment by HeatDeath76** [comment]
I'm actually learning Python right now, and the code here is just enough more advanced than what I've done to be really quite educational.

**Comment by DirtyHairy** [comment]
😆 Just don't expect any best practices there, Python is not my strongest side.

I have released CloudpilotEmu 1.8.9 which fixes the underlying bug; databases are now exported correctly on OS < 3 even if they contain deleted records. I also did a small fix to the script, so you might want to process your broken files with the new version again, just to be 100% sure.

Again, thanks alot for reporting this, I would never have found it. Most of my testing is done with PalmOS 4 devices, and the one that I actually use is a m515 😏
